name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12 horas
  workflow_dispatch:        # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: juanvitor04
          outputs: dist/github-contribution-grid-snake.svg

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
